#!/bin/sh
set -e

APP_DIR="/app"
AUTO_CREATE_NEXT="${AUTO_CREATE_NEXT:-true}"
NEXT_PROJECT_NAME="${NEXT_PROJECT_NAME:-winnicode-next-frontend}"
NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-https://winnicode.test/api}"

cd "$APP_DIR"

create_next_project() {
  echo "⚛️ Creating zero-config Next.js project..."

  mkdir -p "$APP_DIR/src/app"

  cat > "$APP_DIR/package.json" <<EOF
{
  "name": "$NEXT_PROJECT_NAME",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^15.5.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0"
  },
  "devDependencies": {
    "@types/node": "^22.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "typescript": "^5.0.0",
    "eslint": "^9.0.0",
    "eslint-config-next": "^15.5.0"
  }
}
EOF

  cat > "$APP_DIR/next.config.ts" <<'EOF'
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
EOF

  cat > "$APP_DIR/tsconfig.json" <<'EOF'
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

  cat > "$APP_DIR/next-env.d.ts" <<'EOF'
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js.
// Do not edit this file manually.
EOF

  cat > "$APP_DIR/src/app/layout.tsx" <<'EOF'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Winnicode Frontend",
  description: "Next.js frontend for Laravel API",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body>{children}</body>
    </html>
  );
}
EOF

  cat > "$APP_DIR/src/app/page.tsx" <<'EOF'
export default function Home() {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "/api";

  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "48px",
        fontFamily: "Arial, sans-serif",
        background: "#f7f7f7",
      }}
    >
      <section
        style={{
          maxWidth: "760px",
          margin: "0 auto",
          padding: "32px",
          borderRadius: "20px",
          background: "#ffffff",
          boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
        }}
      >
        <p style={{ margin: 0, color: "#666" }}>Laravel API + Next.js</p>
        <h1 style={{ marginTop: "12px", fontSize: "40px" }}>
          Winnicode Next.js Frontend
        </h1>
        <p style={{ fontSize: "18px", lineHeight: 1.7 }}>
          Frontend Next.js berhasil dibuat otomatis oleh Docker.
        </p>
        <p>
          Laravel API:
          <code
            style={{
              display: "inline-block",
              marginLeft: "8px",
              padding: "4px 8px",
              borderRadius: "8px",
              background: "#f0f0f0",
            }}
          >
            {apiUrl}
          </code>
        </p>
      </section>
    </main>
  );
}
EOF

  cat > "$APP_DIR/.env.local" <<EOF
NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
EOF

  cat > "$APP_DIR/.gitignore" <<'EOF'
node_modules
.next
out
.env*.local
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*
EOF

  echo "✅ Next.js project files created."
}

if [ ! -f "$APP_DIR/package.json" ]; then
  if [ "$AUTO_CREATE_NEXT" = "true" ]; then
    create_next_project
  else
    echo "❌ package.json not found and AUTO_CREATE_NEXT=false."
    exit 1
  fi
else
  echo "✅ Next.js package.json already exists."
fi

if [ ! -d "$APP_DIR/node_modules/next" ]; then
  echo "📦 Installing Next.js dependencies..."
  npm install
else
  echo "✅ Next.js dependencies already installed."
fi

echo "🚀 Starting Next.js..."
exec "$@"
